version: "3"

services:
  sonarqube:
    image: sonarqube:community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:


# version: "3"

# services:
#   sonarqube:
#     image: sonarqube:lts
#     container_name: sonarqube
#     ports:
#       - 9000:9000
#     networks:
#       - sonarnet
#     environment:
#       - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
#       - SONARQUBE_JDBC_USERNAME=sonar
#       - SONARQUBE_JDBC_PASSWORD=sonar
#     volumes:
#       - sonarqube_conf:/opt/sonarqube/conf
#       - sonarqube_data:/opt/sonarqube/data
#       - sonarqube_extensions:/opt/sonarqube/extensions
#       - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
#       - /Users/vikash/sonarqube-community-branch-plugin-1.3.1.jar:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin.jar
#       - /Users/vikash/sonarqube-community-branch-plugin-1.3.1.jar:/opt/sonarqube/lib/common/sonarqube-community-branch-plugin.jar

#   db:
#     image: postgres:11.5
#     container_name: postgres
#     ports:
#       - 5432:5432
#     networks:
#       - sonarnet
#     environment:
#       - POSTGRES_USER=sonar
#       - POSTGRES_PASSWORD=sonar
#     volumes:
#       - postgresql:/var/lib/postgresql
#       - postgresql_data:/var/lib/postgresql/data

# networks:
#   sonarnet:

# volumes:
#   sonarqube_conf:
#   sonarqube_data:
#   sonarqube_extensions:
#   sonarqube_bundled-plugins:
#   postgresql:
#   postgresql_data: