const WelcomeTemplate = (first_name: any, nc_name: any, nc_full_name: any, nc_email: any) => {
    return `<!DOCTYPE html>
<div style='margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 13.2px; line-height: inherit; font-family: "Segoe UI", "Segoe UI Web (West European)", "Segoe UI", -apple-system, BlinkMacSystemFont, Roboto, "Helvetica Neue", sans-serif; vertical-align: baseline; color: rgb(50, 49, 48); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
    <p style="font-size: 11pt; font-family: Calibri, sans-serif; margin: 0px;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13.5pt; line-height: inherit; font-family: tahoma, sans-serif; vertical-align: baseline; color: inherit;">Hi ${first_name},</span></p>
    <p style="font-size: 11pt; font-family: Calibri, sans-serif; margin: 0px;"><br></p>
</div>
<div style='margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 13.2px; line-height: inherit; font-family: "Segoe UI", "Segoe UI Web (West European)", "Segoe UI", -apple-system, BlinkMacSystemFont, Roboto, "Helvetica Neue", sans-serif; vertical-align: baseline; color: rgb(50, 49, 48); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
    <div style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: inherit;">
        <div style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: inherit;">
            <p style="margin: 0px;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: tahoma, sans-serif; vertical-align: baseline; color: rgb(34, 34, 34);">Welcome to&nbsp;</span><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: tahoma, sans-serif; vertical-align: baseline; color: inherit;"><a data-auth="NotApplicable" data-linkindex="2" href="https://www.vitawerks.com/" rel="noopener noreferrer" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;" target="_blank"><strong><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 11pt; line-height: inherit; font-family: inherit; vertical-align: baseline; color: inherit;">Vitawerks</span></strong></a></span><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: tahoma, sans-serif; vertical-align: baseline; color: rgb(34, 34, 34);">! We are excited to have you onboard and start your journey with us.</span></p>
            <p style="margin: 0px;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: tahoma, sans-serif; vertical-align: baseline; color: rgb(34, 34, 34);">I am ${nc_name}, your dedicated&nbsp;</span><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: tahoma, sans-serif; vertical-align: baseline; color: inherit;"><a data-auth="NotApplicable" data-linkindex="3" href="https://www.vitawerks.com/clinician" rel="noopener noreferrer" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;" target="_blank"><strong><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 11pt; line-height: inherit; font-family: inherit; vertical-align: baseline; color: inherit;">Nurse Champion</span></strong></a></span><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: tahoma, sans-serif; vertical-align: baseline; color: rgb(34, 34, 34);">.</span></p>
            <p style="margin: 0px;"><br></p>
            <p style="margin: 0px;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: tahoma, sans-serif; vertical-align: baseline; color: rgb(34, 34, 34);">I will be serving as your key point of contact here at Vitawerks. I would like to make sure you get the best shifts at the best rate and on a schedule that works best for you.&nbsp;</span><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: tahoma, sans-serif; vertical-align: baseline; color: black;">I am going to be there with you every step of the way to answer all your questions in real-time.</span></p>
            <p style="margin: 0px;"><br></p>
            <p style="margin: 0px;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: tahoma, sans-serif; vertical-align: baseline; color: black;">Please refer to the handbook for instructions/guidelines on filling up the <strong>timesheet</strong>. This is an important document for our records and to comply with state laws. It is mandatory to submit/email your timesheet to&nbsp;</span><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: tahoma, sans-serif; vertical-align: baseline; color: rgb(17, 85, 204);"><a data-auth="NotApplicable" data-linkindex="4" href="mailto:account@vitawerks.com" rel="noopener noreferrer" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;" target="_blank">account@vitawerks.com</a></span><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: tahoma, sans-serif; vertical-align: baseline; color: rgb(34, 34, 34);">&nbsp;</span><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: tahoma, sans-serif; vertical-align: baseline; color: black;">so that we can issue you payment for your shift as per the hours worked in the facility.&nbsp;</span></p>
            <p style="margin: 0px;"><br></p>
            <p style="margin: 0px;"><strong><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: tahoma, sans-serif; vertical-align: baseline; color: black;">Timesheets</span></strong><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: tahoma, sans-serif; vertical-align: baseline; color: black;">&nbsp;should be duly filled and must include the name of the registry (VitaWerks), facility, DSD and charge nurse, and a signature from DSD or charge nurse at the end of the shift. The <strong>timesheet</strong> should have the date of shift, clock in clock out time, and break time filled out. It is essential to take your 30 mins to break during the shift at the facility. If they are unable to take a break for any reason please let us know so that we can inform the facility. Timesheets will not be accepted if any of this information is missing.</span></p>
            <p style="margin: 0px;"><br></p>
            <p style="margin: 0px;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: tahoma, sans-serif; vertical-align: baseline; color: inherit;">&nbsp;</span><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: tahoma, sans-serif; vertical-align: baseline; color: black;">You will also be receiving an email to set up your direct deposit. For any payroll questions or concerns, please contact (818) 722-1304.</span></p>
            <p style="margin: 0px;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: tahoma, sans-serif; vertical-align: baseline; color: inherit;">&nbsp;</span></p>
            <p style="margin: 0px;"><br></p>
            <p style="margin: 0px;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: tahoma, sans-serif; vertical-align: baseline; color: rgb(34, 34, 34);">Feel free to reach out to me if you need further clarifications on anything. I am available at 818 722 1311 for a chat/call. In case I am not available, please call our company line at 818 722 1230. Text is always a good way to get quick responses.</span></p>
            <p style="margin: 0px;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: tahoma, sans-serif; vertical-align: baseline; color: inherit;">&nbsp;</span></p>
            <p style="margin: 0px;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: tahoma, sans-serif; vertical-align: baseline; color: black;">Welcome again to the family!</span></p>
            <p style="margin: 0px;"><br></p>
            <p style="margin: 0px;"><br></p>
            <table border="0" cellpadding="0" cellspacing="0" style='font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 13.2px; line-height: inherit; font-family: "Segoe UI", "Segoe UI Web (West European)", "Segoe UI", -apple-system, BlinkMacSystemFont, Roboto, "Helvetica Neue", sans-serif; color: rgb(50, 49, 48); letter-spacing: normal; orphans: 2; text-align: start; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; border-collapse: collapse; background-repeat: initial; background-position: initial; background-image: initial;'>
                <tbody>
                    <tr style="height: 36pt;">
                        <td style="white-space: normal !important; height: 36pt; padding: 1.5pt 2.25pt; border: 1pt solid white;">
                            <p style="font-size: 11pt; font-family: Calibri, sans-serif; margin: 0px;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 10pt; line-height: inherit; font-family: Helvetica; vertical-align: baseline; color: inherit;"><img data-imagetype="External" src="https://drive.google.com/uc?id=1gG4gzxtrHmNryORZ8MN8YviJhkuFjT5-&export=download" border="0" style="padding: 0px; border: 0px; font: inherit; color: inherit; width: 72pt; height: 56.24pt;"></span></p>
                            <p style="font-size: 11pt; font-family: Calibri, sans-serif; margin: 0px;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 10pt; line-height: inherit; font-family: Helvetica; vertical-align: baseline; color: inherit;">&nbsp; &nbsp; &nbsp;</span></p>
                        </td>
                        <td style="white-space: normal !important; width: 152.8pt; height: 36pt; padding: 1.5pt 2.25pt; border-width: 1pt; border-style: solid solid solid none; border-color: white;" valign="bottom">
                            <p style="font-size: 11pt; font-family: Calibri, sans-serif; margin: 0px 0px 0px 14.4pt;"><strong><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 10pt; line-height: inherit; font-family: Arial, sans-serif; vertical-align: baseline; color: black;">${nc_full_name}</span></strong></p>
                            <p style="font-size: 11pt; font-family: Calibri, sans-serif; margin: 0px 0px 0px 14.4pt;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 10pt; line-height: inherit; font-family: Arial, sans-serif; vertical-align: baseline; color: black;">Account Manager</span></p>
                            <p style="font-size: 11pt; font-family: Calibri, sans-serif; margin: 0px 0px 0px 14.4pt;">(818) 860 0372</p>
                            <p style="font-size: 11pt; font-family: Calibri, sans-serif; margin: 0px 0px 0px 14.4pt;"><a data-auth="NotApplicable" data-linkindex="8" href="mailto:recruitment4@vitawerks.com" rel="noopener noreferrer" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;" target="_blank">${nc_email}</a></p>
                            <p style="font-size: 11pt; font-family: Calibri, sans-serif; margin: 0px 0px 0px 14.4pt;"><a data-auth="NotApplicable" data-linkindex="9" href="http://vitawerks.com/" rel="noopener noreferrer" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;" target="_blank">vitawerks.com</a></p>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
</html>`
}

export {WelcomeTemplate}