on:
  push:
    branches:
      - master       # The default branch
      # - branch-* 
name: Main Workflow
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - name: Check out my other private repo
      uses: actions/checkout@master
      with:
        repository: tericsoft-services/vitawerks_automation 
        token: ${{ secrets.my_pat }}
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1 # Setup JAVA
      with:
        java-version: 1.8
    - name: Install Google Chrome # Using shell script to install Google Chrome
      run: |
        chmod +x ./InstallChrome.sh
        ./InstallChrome.sh
    - name: Run tests  
      run: mvn test -Dtest=Pipeline1_Web_Smoke  
