on:
  push:
    branches:
      - main
name: Main Workflow
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: joschi/setup-jdk@v2
      with:
        java-version: '11' # The OpenJDK version to make available on the path
        architecture: 'x64' # defaults to 'x64'
    - run: java -cp java HelloWorldApp
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@v1.1.0
      with:
        host: ${{ secrets.SONARQUBE_HOST }}
        login: ${{ secrets.SONARQUBE_TOKEN }}
        # path: ${{secrets.SONAR_PATH}}